language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "ispw-becrafter"
    token:
      secure: "b6b6ecccdda5812f20f6b6e4302a3f60880aa771"
script: 
  - ant build
  - sonar-scanner